name: 'setup_cache'
description: 'Sets up the shared cache for Conan and pip'
inputs:
  compiler:
    required: true
    type: string
  build_type:
    required: true
    type: string
  developer_mode:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Cache Conan and pip
      uses: actions/cache@v4
      with:
        # Cache Conan packages
        path: |
          ${{ env.CONAN_USER_HOME }}
          ~/.cache/pip
        key: ${{ runner.os }}-${{ inputs.compiler }}-${{ inputs.build_type }}-${{ hashFiles('conanfile.txt') }}-${{ inputs.developer_mode }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.compiler }}-${{ inputs.build_type }}-