name: Windows CI

on:
  pull_request:

  release:
    types: [published]

  push:
    branches:
      - main
      - develop

env:
  CONAN_SYSREQUIRES_MODE: enabled
  CONAN_USER_HOME: ${{ github.workspace }}/conan-cache
  CONAN_USER_HOME_SHORT: ${{ github.workspace }}/conan-cache/short

jobs:
  Test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - windows-2022
          - windows-2025-vs2026

        compiler:
          - msvc

        build_type:
          - Release
          - Debug

        developer_mode:
          - ON
          - OFF

        standard:
          - 17
          - 20
          - 23

        include:
          - compiler: msvc
            build_type: Release
            developer_mode: OFF
            package_generator: ZIP

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Cache
        uses: ./.github/actions/setup_cache
        with:
          compiler: ${{ matrix.compiler }}
          build_type: ${{ matrix.build_type }}
          developer_mode: ${{ matrix.developer_mode }}

      - name: Setup C++
        uses: aminya/setup-cpp@v1
        with:
          vcvarsall: true
          cmake: true
          ninja: true
          conan: true
          vcpkg: false
          ccache: true
          clangtidy: true
          cppcheck: true
          gcovr: true
          opencppcoverage: true

      - name: Detect default Conan profile
        run: conan profile detect

      - name: Install dependencies
        run: >
          conan install . -of build
          --build missing
          -s:h build_type=${{ matrix.build_type }}
          -s:h compiler.cppstd=${{ matrix.standard }}
          -s:b build_type=${{ matrix.build_type }}
          -s:b compiler.cppstd=${{ matrix.standard }}
          -c tools.cmake.cmaketoolchain:generator=Ninja

      - name: Configure CMake
        uses: nick-invision/retry@v3
        with:
          max_attempts: 3
          retry_wait_seconds: 10
          timeout_minutes: 2
          shell: bash
          command: |
            cmake \
              -S . \
              -B build \
              -G Ninja \
              -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -DENABLE_DEVELOPER_MODE=${{ matrix.developer_mode }} \
              -DENABLE_COVERAGE=$([[ "${{ matrix.build_type }}" == "Debug" ]] && echo ON || echo OFF) \
              -DCMAKE_CXX_STANDARD=${{ matrix.standard }} \
              -DGIT_SHA=${{ github.sha }}

      - name: Build
        run: cmake --build build --verbose

      - name: Test and coverage
        if: matrix.build_type == 'Debug'
        working-directory: build
        shell: pwsh
        run: |
          OpenCppCoverage.exe --export_type cobertura:coverage.xml --cover_children -- `
            ctest --output-on-failure

      - name: CPack
        if: matrix.package_generator != ''
        working-directory: build
        run: |
          cpack -C ${{ matrix.build_type }} -G ${{ matrix.package_generator }}

      - name: Publish Tagged Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/*-*${{ matrix.build_type }}*-*.*

      - name: Publish to Codecov
        if: matrix.build_type == 'Debug'
        uses: codecov/codecov-action@v5
        with:
          files: build/coverage.xml
          flags: windows
          name: windows-coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false